### ISSUE TITLE
Error en planificador.md

### ISSUE THREAD

**Issue by emanuelcasco** [sisoputnfrba/2018-1c-re-distinto#4]
En la descripción del planificador el **"Puerto de Conexión al Coordinador" debería ser 8001**, no 8000.

https://github.com/sisoputnfrba/2018-1c-re-distinto/blob/ab1bae58f5e72c0fd3b3d6b9d46ab978c2564bc1/planificador.md#L46-L55

**Comment by afilgueira** [comment]
Hola, porqué estaría mal? Es este puerto:

https://github.com/sisoputnfrba/2018-1c-re-distinto/blob/ab1bae58f5e72c0fd3b3d6b9d46ab978c2564bc1/coordinador.md#L52-L60

**Comment by davidosvaldoperez** [comment]
Holas! Creo que el problema mas bien esta aca:

Campo | Tipo | Ejemplo 
--- | --- | ---
Puerto de Escucha de conexiones   | [numérico]                   | `8000`
Puerto de Conexión al Coordinador | [numérico]                   | `8000` (**tambien**?)

La propuesta seria que el puerto de escucha de conexiones **del planificador** sea el 8001. Asi tambien concuerda con la [configuracion del ESI](https://github.com/sisoputnfrba/2018-1c-re-distinto/blob/ab1bae58f5e72c0fd3b3d6b9d46ab978c2564bc1/ejecutor-sentencias-interactivas.md#configuraci%C3%B3n).

**Comment by afilgueira** [comment]
Ok, ese es otro puerto entonces. Si, podría ser 8001. A fines prácticos los archivos están a modo de ejemplo pero si confunde podemos actualizarlo.

**Comment by iago64** [comment]
Esta corregido y listo para subir en la próxima errata, así no confundimos :)

**Comment by iago64** [comment]
Subio el cambio en la errata, se cierra el issue :)
